
import Order.DetailOrder;
import Order.AddCount;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template


//import java.awt.Dimension;
//import java.awt.Toolkit;

/**
 *
 * @author imamkahih
 */
public class choose_menues extends javax.swing.JFrame {

    /**
     * Creates new form choose_menues
     */
    public choose_menues() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nasiGorengButton = new javax.swing.JButton();
        sateAyamButton = new javax.swing.JButton();
        ayamBakarButton = new javax.swing.JButton();
        mieGorengButton = new javax.swing.JButton();
        tehBotolButton = new javax.swing.JButton();
        esTehManisButton = new javax.swing.JButton();
        kwetiauButton = new javax.swing.JButton();
        ayamGorengButton = new javax.swing.JButton();
        esJerukButton = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+28));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KASIR RESTORAN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        nasiGorengButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nasiGorengButton.setText("Nasi Goreng");
        nasiGorengButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nasiGorengButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasiGorengButtonActionPerformed(evt);
            }
        });

        sateAyamButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sateAyamButton.setText("Sate Ayam");
        sateAyamButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sateAyamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sateAyamButtonActionPerformed(evt);
            }
        });

        ayamBakarButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ayamBakarButton.setText("Ayam Bakar");
        ayamBakarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayamBakarButtonActionPerformed(evt);
            }
        });

        mieGorengButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mieGorengButton.setText("Mie Goreng");
        mieGorengButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mieGorengButtonActionPerformed(evt);
            }
        });

        tehBotolButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tehBotolButton.setText("Teh Botol");
        tehBotolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tehBotolButtonActionPerformed(evt);
            }
        });

        esTehManisButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        esTehManisButton.setText("Es Teh Manis");
        esTehManisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esTehManisButtonActionPerformed(evt);
            }
        });

        kwetiauButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        kwetiauButton.setText("Kwetiau");
        kwetiauButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kwetiauButtonActionPerformed(evt);
            }
        });

        ayamGorengButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ayamGorengButton.setText("Ayam Goreng");
        ayamGorengButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayamGorengButtonActionPerformed(evt);
            }
        });

        esJerukButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        esJerukButton.setText("Es Jeruk");
        esJerukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esJerukButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tehBotolButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sateAyamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nasiGorengButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ayamBakarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mieGorengButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(esTehManisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kwetiauButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ayamGorengButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(esJerukButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nasiGorengButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(mieGorengButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kwetiauButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ayamBakarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(sateAyamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ayamGorengButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tehBotolButton, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(esTehManisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(esJerukButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton10.setText("Next");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
this.setExtendedState(this.MAXIMIZED_BOTH);     // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
DetailOrder asd = new DetailOrder();
asd.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void nasiGorengButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasiGorengButtonActionPerformed
//        AddCount ac = new AddCount(0);
//        ac.setVisible(true);
    }//GEN-LAST:event_nasiGorengButtonActionPerformed

    private void mieGorengButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mieGorengButtonActionPerformed
//        AddCount ac = new AddCount(1);
//        ac.setVisible(true);
    }//GEN-LAST:event_mieGorengButtonActionPerformed

    private void kwetiauButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kwetiauButtonActionPerformed
//        AddCount ac = new AddCount(2);
//        ac.setVisible(true);
    }//GEN-LAST:event_kwetiauButtonActionPerformed

    private void sateAyamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sateAyamButtonActionPerformed
//        AddCount ac = new AddCount(3);
//        ac.setVisible(true);
    }//GEN-LAST:event_sateAyamButtonActionPerformed

    private void ayamBakarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayamBakarButtonActionPerformed
//        AddCount ac = new AddCount(4);
//        ac.setVisible(true);
    }//GEN-LAST:event_ayamBakarButtonActionPerformed

    private void ayamGorengButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayamGorengButtonActionPerformed
//        AddCount ac = new AddCount(5);
//        ac.setVisible(true);
    }//GEN-LAST:event_ayamGorengButtonActionPerformed

    private void tehBotolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tehBotolButtonActionPerformed
//        AddCount ac = new AddCount(6);
//        ac.setVisible(true);
    }//GEN-LAST:event_tehBotolButtonActionPerformed

    private void esTehManisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esTehManisButtonActionPerformed
//        AddCount ac = new AddCount(7);
//        ac.setVisible(true);
    }//GEN-LAST:event_esTehManisButtonActionPerformed

    private void esJerukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esJerukButtonActionPerformed
//        AddCount ac = new AddCount(8);
//        ac.setVisible(true);
    }//GEN-LAST:event_esJerukButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choose_menues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choose_menues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choose_menues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choose_menues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choose_menues().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ayamBakarButton;
    private javax.swing.JButton ayamGorengButton;
    private javax.swing.JButton esJerukButton;
    private javax.swing.JButton esTehManisButton;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kwetiauButton;
    private javax.swing.JButton mieGorengButton;
    private javax.swing.JButton nasiGorengButton;
    private javax.swing.JButton sateAyamButton;
    private javax.swing.JButton tehBotolButton;
    // End of variables declaration//GEN-END:variables
}
